### ISSUE TITLE
Mix route types

### ISSUE THREAD

**Issue by deiberchacon** [tmuguet/lrm-straightline#2]
How can I mix routes with straight lines and without straight lines in the same map? That is, if I have road mode routes (without straight lines) and one that is an airport-airport flight (with a straight line).

**Comment by tmuguet** [comment]
Hi,

It really depends on how you construct the routes.

If you're using the vanilla control from Leaflet Routing Machine, I guess it's not supported out-of-the-box but I may be wrong. Best would be to check with the Leaflet Routing Machine team how to support multiple routers.

Otherwise, programmatically, it's just a matter of calling both routers and display the two results.

**Comment by deiberchacon** [comment]
Hi @tmuguet  

Thank you for your answer. I found the way to support multiple route modes. 

My solution is this: 

1. Separate the waypoints for vanilla and straight line routes.
2. Create a routing control for each mode.
3. Use `router: new L.Routing.StraightLine()` only for the straight lines control.

It can be done from Leaflet Routing Machine, there is no problem with **lrm-straightline**.
